[default]
extend-ignore-re = [
  "(?Rm)^.*(?:#|//|--)\\s*typo-ignore:this-line$",
  "(?:#|//|--)\\s*typo-ignore:next-line\\s*\\n.*",
  "(?s)(?:#|//|--)\\s*typo-ignore:on.*?(?:#|//|--)\\s*typo-ignore:off",
]
