return {
  name = 'harper-ls',
  cmd = { 'harper-ls', '--stdio' },
  filetypes = {
    'markdown',
    'rust',
    'typescript',
    'typescriptreact',
    'javascript',
    'python',
    'go',
    'c',
    'cpp',
    'ruby',
    'swift',
    'csharp',
    'toml',
    'lua',
  },
  root_markers = { '.git' },
  settings = {
    ['harper-ls'] = {
      linters = {
        spell_check = true,
        spelled_numbers = false,
        an_a = true,
        sentence_capitalization = true,
        unclosed_quotes = true,
        wrong_quotes = false,
        long_sentences = true,
        repeated_words = true,
        spaces = true,
        matcher = true,
      },
    },
  },
}
