return {
  name = 'harper-ls',
  cmd = { 'harper-ls', '--stdio' },
  filetypes = {
    'markdown',
    'rust',
    'typescript',
    'typescriptreact',
    'javascript',
    'python',
    'go',
    'c',
    'cpp',
    'ruby',
    'swift',
    'csharp',
    'toml',
    'lua',
  },
  root_markers = { '.git' },
  settings = {
    ['harper-ls'] = {
      linters = {
        -- https://writewithharper.com/docs/rules
        SpellCheck = true,
        SpelledNumbers = false,
        AnA = true,
        SentenceCapitalization = false,
        UnclosedQuotes = false,
        WrongQuotes = false,
        LongSentences = false,
        RepeatedWords = true,
        Spaces = true,
        Matcher = true,
        CorrectNumberSuffix = true,
        OrthographicConsistency = false,
        ExpandArgument = false,
      },
    },
  },
}
